from __future__ import annotations

from typing import final

class ConfigError(ValueError): ...
class FrameError(ValueError): ...
class TransportError(RuntimeError): ...

@final
class RawEthernetConfig:
    def __init__(
        self,
        interface_name: str,
        host_mac: str,
        host_ip: str,
        host_udp_port: int,
        board_mac: str,
        board_ip: str,
        board_udp_port: int,
        ring_capacity: int,
        schema_version: int = 2,
    ) -> None: ...
    @property
    def schema_version(self) -> int: ...
    @property
    def interface_name(self) -> str: ...
    @property
    def host_mac(self) -> str: ...
    @property
    def host_ip(self) -> str: ...
    @property
    def host_udp_port(self) -> int: ...
    @property
    def board_mac(self) -> str: ...
    @property
    def board_ip(self) -> str: ...
    @property
    def board_udp_port(self) -> int: ...
    @property
    def ring_capacity(self) -> int: ...
    @property
    def maximum_udp_payload_bytes(self) -> int: ...

@final
class ReceivedDatagram:
    @property
    def payload(self) -> bytes: ...
    @property
    def sender_ip(self) -> str: ...
    @property
    def sender_udp_port(self) -> int: ...

@final
class TransportStatistics:
    @property
    def receive_ready(self) -> bool: ...
    @property
    def sent_frames(self) -> int: ...
    @property
    def received_frames(self) -> int: ...
    @property
    def receive_timeouts(self) -> int: ...
    @property
    def dropped_frames(self) -> int: ...
    @property
    def kernel_dropped_frames(self) -> int: ...
    @property
    def ignored_outgoing_frames(self) -> int: ...
    @property
    def ignored_non_ipv4_frames(self) -> int: ...
    @property
    def invalid_frames(self) -> int: ...
    @property
    def foreign_frames(self) -> int: ...
    @property
    def maximum_queue_depth(self) -> int: ...
    @property
    def queue_capacity(self) -> int: ...
    @property
    def receive_buffer_bytes(self) -> int | None: ...
    def frame_classification(self) -> dict[str, int]: ...

@final
class RawEthernetClient:
    def __init__(self, config: RawEthernetConfig) -> None: ...
    def send(self, payload: bytes) -> None: ...
    def receive(self, timeout_seconds: float) -> ReceivedDatagram: ...
    def statistics(self) -> TransportStatistics: ...
    def close(self) -> None: ...
    @property
    def closed(self) -> bool: ...
    def __enter__(self) -> RawEthernetClient: ...
    def __exit__(self, exc_type: object, exc_value: object, traceback: object) -> None: ...

def build_udp_frame(
    config: RawEthernetConfig,
    payload: bytes,
    ipv4_identification: int = 0,
) -> bytes: ...

def parse_udp_frame(config: RawEthernetConfig, frame: bytes) -> ReceivedDatagram | None: ...
