[package]
name = "ccsds-frame-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
ccsds-ethernet-client = { path = ".." }

[[bin]]
name = "frames"
path = "fuzz_targets/frames.rs"
test = false
doc = false
bench = false

[workspace]
